### ISSUE TITLE
Unable to find libfuse when run "auto_run.py"

### ISSUE THREAD

**Issue by zchen71** [opendilab/DI-drive#26]
I tried to run "auto_run.py" on windows and got issues as follow:

_Traceback (most recent call last):
  File "simple_rl_train.py", line 9, in <module>
    from core.envs import SimpleCarlaEnv, BenchmarkEnvWrapper
  File "d:\carla\di-drive\core\envs\__init__.py", line 24, in <module>
    from .md_macro_env import MetaDriveMacroEnv
  File "d:\carla\di-drive\core\envs\md_macro_env.py", line 12, in <module>
    from core.utils.simulator_utils.md_utils.discrete_policy import DiscreteMetaAction
  File "d:\carla\di-drive\core\utils\simulator_utils\md_utils\discrete_policy.py", line 5, in <module>
    from metadrive.component.vehicle_module.PID_controller import PIDController
  File "C:\Users\James Chen\anaconda3\envs\carla_1\lib\site-packages\metadrive\__init__.py", line 11, in <module>
    _module = loader.find_module(module_name).load_module(module_name)
  File "C:\Users\James Chen\anaconda3\envs\carla_1\lib\site-packages\metadrive\cli.py", line 14, in <module>
    from metadrive.mnt import mount
  File "C:\Users\James Chen\anaconda3\envs\carla_1\lib\site-packages\metadrive\mnt.py", line 7, in <module>
    from fuse import FUSE, FuseOSError, Operations
  File "C:\Users\James Chen\anaconda3\envs\carla_1\lib\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse_

I am wondering whether the problem is caused by windows? and any solutions? Solutions I can find online are all based on Linux.

Thanks!

**Comment by RobinC94** [comment]
This error usually happens when you don't have the fuse package installed.

On Ubuntu, you can install this with:
```
sudo apt-get update && sudo apt-get install fuse
```
On Centos:
```
yum install libfuse python
```

While I couldn't find such installation command on Win, maybe you can try with ```pip```:
```
pip install fusepy
```
If this didn't work then, try referring to documents of libfuse(https://github.com/libfuse/libfuse) for help.

After installed, it should work. :)
